name: connect4_flutter

description: A modern Connect Four game with beautiful UI and sound effects.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  web_socket_channel: ^2.4.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  cloud_firestore: ^4.14.0
  intl: ^0.19.0

# Add dev dependencies here.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/conecta4_logo.png
    - assets/sounds/music/main_theme.mp3
    - assets/sounds/effects/piece_drop.mp3
    - assets/sounds/effects/win_celebration.mp3
    - assets/sounds/ui/button_click.mp3
    - assets/sounds/ui/timer_tick.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Connect-Four-Logo-Slide-scaled.jpg"
